### ISSUE TITLE
Form -> Input component looses all its styles when used as type='number'

### ISSUE THREAD

**Issue by siddhantk232** [dailykit/dailykit-ui#31]
The ```<Field />``` component is only applying some styling for the ``` email | text | email``` type of inputs. In the recipe-app we also need the input of ```type="number"```.

**Comment by prvnbist** [comment]
I'll include it as a value for prop `type` but we most likely wont use input of type number since it can't handle no's with spaces and browser defaults assume that all number inputs require a stepper. 

More on this issue if interested - https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

**Comment by siddhantk232** [comment]
Didn't knew about this and thanks for sharing the article :)
